---
title: "02_eda"
format: html
---

Libraries.

```{r }
library(nanoparquet)
library(fs)
library(tibble)
library(ggplot2)
```

# Data

Load data.

```{r }
df <- read_parquet(
  file = path(
    config::get("path", config="silver"), config::get("polls", config="silver")
  )
) |> 
  as_tibble()

df
```

# Charts

Voting.

```{r fig.height=5}
ggplot(df, aes(x = date, y = p, color = shortname, group = shortname)) +
  geom_line() +
  # dashed vertical line on New Year’s Eve
  geom_vline(xintercept = as.Date("2024-12-31")) +
  # dotted lines for quarter boundaries
  geom_vline(xintercept = as.Date(c("2024-12-31", "2025-03-31", "2025-06-30", "2025-09-30")),
             linetype = "dotted") +
  scale_y_continuous(labels = scales::label_percent(accuracy = 1)) +
  scale_x_date(
    date_breaks = "1 month",
    date_labels = "%m",   # show month number only
    limits = as.Date(c("2024-10-20", "2025-09-29"))
  ) +
  theme_bw() +
  theme(
    panel.grid.minor = element_blank(),
    axis.text.x = element_text(angle = 0, vjust = 0.5)
  )
```

Attendance

```{r }
df |> 
  select(date, attendance, agency) |> 
  distinct() |> 
  ggplot(aes(x = date, y = attendance, color = agency, group = agency)) +
  geom_line()
```