default:
  polls:   https://{.type}.programydovoleb.cz/polls/all.json
  parties: https://{.type}.programydovoleb.cz/party/fetch/{.id}.json

bronze:
  path:    !expr here::here("data", "bronze")
  polls:   !expr here::here("data", "bronze", "polls.json")
  parties: !expr here::here("data", "bronze", "parties.json")
  
silver:
  path:    !expr here::here("data", "silver")
  polls:   !expr here::here("data", "silver", "polls.parquet")
  parties: !expr here::here("data", "silver", "parties.parquet")
  data:    !expr here::here("data", "silver", "data.parquet")

gold:
  path:           !expr here::here("data", "gold")
  simple_var_ppc: !expr here::here("data", "gold", "simple_var_ppc.rds")