default:
  polls:   https://{.type}.programydovoleb.cz/polls/all
  parties: https://{.type}.programydovoleb.cz/party/fetch/{.id}

bronze:
  path:    !expr here::here("data", "3bronze")
  polls:   !expr here::here("data", "3bronze", "polls.json")
  parties: !expr here::here("data", "3bronze", "parties.json")
  license: !expr here::here("data", "3bronze", "_license.json")
  
silver:
  path:    !expr here::here("data", "2silver")
  polls:   !expr here::here("data", "2silver", "polls.parquet")
  parties: !expr here::here("data", "2silver", "parties.parquet")

gold:
  path:          !expr here::here("data", "1gold")
  mapping:       !expr here::here("data", "1gold", "mapping.json")
  calendar_wide: !expr here::here("data", "1gold", "calendar_wide.parquet")
  calendar_long: !expr here::here("data", "1gold", "calendar_long.parquet")