---
Title: Model
---

# Preparation

Load libraries.

```{r}
# Data loading
library(nanoparquet)
# Data wrangling
library(dplyr)
library(tidyr)
library(tibble)
# Data visualization and representation
library(plotly)
library(stringr)
library(glue)
# Modeling
library(cmdstanr)
library(posterior)
```

Configure cmdstanr.

```{r setup, include=FALSE}
install_cmdstan()
```

# Prepare data

Load data.

```{r}
df_raw <-
  read_parquet(here::here("data", "silver", "data.parquet")) |>
  filter(!is.na(amount))

df_raw
```

Horizontal pivot.

```{r}
df <-
  df_raw |>
  select(date, agency, amount, party, value) |>
  pivot_wider(
    id_cols = c(date, agency, amount),
    names_from = "party",
    values_from = "value"
  ) |>
  rowwise() |>
  mutate(
    "000" = 1 - sum(c_across(`768`:`1298`), na.rm = TRUE)
  ) |>
  ungroup()

df
```

Other/Missing parties.

```{r}
na_parties <-
  df |>
  select(where(\(x) sum(is.na(x)) > 0)) |>
  colnames()

df <-
  df |>
  rowwise() |>
  mutate(
    "000" = sum(c_across(all_of(c(na_parties, "000"))), na.rm = TRUE)
  ) |>
  ungroup() |>
  select(-all_of(na_parties))

df
```

Mapping.

```{r}
house_list <- list(
  "Kantar" = 1,
  "STEM" = 2,
  "NMS Market Research" = 3,
  "Ipsos" = 4,
  "Median" = 5
)

party_list <-
  df_raw |>
  filter(party %in% colnames(df)) |>
  distinct(party, name) |>
  mutate(name = as.character(name)) |>
  deframe()

party_list <- c(party_list, c(`000` = "Ostatní"))
party_list
```

Map agencies.

```{r}
df <-
  df |>
  mutate(
    agency = unlist(house_list[agency])
  )

df
```

Create calendar of all possibilities

```{r}
calendar_raw <-
  tibble(
    date = seq(min(df$date), max(df$date), by = "day")
  ) |>
  mutate(
    t = row_number()
  ) |>
  cross_join(
    y = tibble(agency = seq_along(house_list))
  )

calendar_raw
```

Join all.

```{r}
calendar <-
  calendar_raw |>
  left_join(df, by = join_by(date, agency), relationship = "one-to-one") |>
  na.omit()

calendar
```

# Model

Model definition.

$$
\begin{aligned}
y_{t, c}               &\sim Dir(\theta_{t, c} \cdot s_{t, c})              \\ % Data likelihood
s_{t, c}               &=    N_{t, c}*\exp(\kappa_{t, c})                   \\ % Poll precision
\kappa_{t, c}          &\sim N(\overline\mu_\kappa, \overline\sigma_\kappa) \\ % Prior for precision for each pollster
\overline\mu_\kappa    &\sim N(0, \sigma=0.2)                               \\ % Hyperparameter
\overline\sigma_\kappa &\sim Exp(2)                                         \\ % Decompose into party-error and pollster-error
\theta_{t, c}          &= Softmax(\alpha_t + \delta_c)                      \\ % Decompose into party-error and pollster-error
\delta_c               &\sim N(0, 1)                                        \\ % Prior for house bias
\sum \delta_c          &= 0, \space\forall\space c = 1, \dots, C            \\ % Zero-to-sum constraint
\alpha_t               &\sim N_P(\alpha_{t-1}, \Sigma)                      \\ % How to compute likelihood for data
\Sigma                 &= diag(\sigma) \cdot \Omega \cdot diag(\sigma)      \\ % Variance decomposition
\sum \alpha_t          &= 0, \space\forall\space t = 1, ..., T              \\ % Zero-to-sum constraint (Softmax is invariant)
\end{aligned}
$$

Model definition.

```{r}
mod <- cmdstan_model(here::here("models", "model.stan"))

stan_data <- list(
  T = max(calendar$t),
  K = nrow(calendar),
  P = length(party_list),
  C = length(house_list),
  y = as.matrix(select(calendar, all_of(names(party_list)))),
  day = calendar$t,
  c = calendar$agency,
  n = calendar$amount
)
```

## Predictive Prior Checks

```{r}
fit_ppc <- mod$sample(
  data = stan_data,
  fixed_param = TRUE,
  iter_sampling = 500,
  chains = 1
)
```

### Estimation of polls

```{r}
y_sim_draws <- fit_ppc$draws("y_sim")
y_sim_summary <- summarise_draws(
  y_sim_draws,
  mean,
  ~ quantile(.x, probs = c(0.055, 0.945))
)

y_sim_df <-
  y_sim_summary |>
  mutate(
    day = as.integer(str_extract(
      variable,
      r"(y\_sim\[(\d+),(\d+)\])",
      group = 1
    )),
    day_true = calendar$t[day],
    party = as.integer(str_extract(
      variable,
      r"(y\_sim\[(\d+),(\d+)\])",
      group = 2
    )),
    party_name = party_list[party]
  )

plot_ly(
  data = y_sim_df,
  x = ~day_true,
  y = ~mean,
  color = ~party_name,
  type = "scatter",
  mode = "lines+markers",
  text = ~ glue(
    "Party: {party_name}<br>",
    "Mean: {round(mean * 100, 1)} %<br>",
    "q_5.5: {round(`5.5%` * 100, 1)} %<br>",
    "q_94.5: {round(`94.5%` * 100, 1)} %<br>"
  ),
  hoverinfo = "text"
) |>
  add_ribbons(
    x = ~day_true,
    ymin = ~`5.5%`,
    ymax = ~`94.5%`,
    color = ~party_name,
    line = list(width = 1),
    opacity = 0.8,
    showlegend = FALSE
  ) |>
  layout(
    yaxis = list(title = "Percentage", tickformat = ".0%"),
    legend = list(orientation = "h", x = 0.5, xanchor = "center", y = -0.2)
  )
```

